### ISSUE TITLE
关于无法删除缓存，整理桌面的bug

### ISSUE THREAD

**Issue by Hz6826** [Ianzb/program#2]
使用开始整理+清理功能，只清空回收站，日志如下
[WARNING 2023-11-29 23:05:33,123 functions.py 2896]:无法整理C:\Users\Admin\Desktop文件夹
[WARNING 2023-11-29 23:05:33,174 functions.py 2896]:文件C:\Users\Admin\AppData\Local\Temp\****无法删除
*similar lines repeat over 100 times

而程序显示清理成功，初步怀疑权限不足，管理员提权后仍报错，进一步排查中……

**Comment by Ianzb** [comment]
缓存部分清理不了很正常不是bug，你看一下为什么桌面整理失败

**Comment by Hz6826** [comment]
Okay
